/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/stage/stage3.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stage(props) {
  const { nodes, materials } = useGLTF('./models/stage/stage3.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-71.669, 8.762, 15.964]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.97, 2.942, 3.954]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.body02_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -155.076, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.body_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.dr01_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -111.852, 95.582]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.dr02_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -60.883, 93.56]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.dr03_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -121.429, 91.907]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.dr04_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -120.549, 91.648]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.hd01_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.hd02_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.hd03_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.ling_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.ling_low002_Material__2_0.geometry} material={materials.Material__2} position={[-0.956, 135.104, 294.491]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.ling_low003_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.ling_low004_Material__2_0.geometry} material={materials.Material__2} position={[-0.956, 151.543, 306.266]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.st01_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.st02_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -2.637, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.st03_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -76.386, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.st04_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -208.238, 310.756]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.stairs_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -205.475, 309.466]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.stl01_low_Material__2_0.geometry} material={materials.Material__2} position={[0, 77.82, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.stl02_low_Material__2_0.geometry} material={materials.Material__2} position={[0, 35.643, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd01_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd01_low_Material__2_0001.geometry} material={materials.Material__2} position={[0, -189.308, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd02_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd03_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd04_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wd05_low_Material__2_0.geometry} material={materials.Material__2} position={[0, 16.455, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wdf_low_Material__2_0.geometry} material={materials.Material__2} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wdl01_low_Material__2_0.geometry} material={materials.Material__2} position={[0, 156.388, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wdl02_low_Material__2_0.geometry} material={materials.Material__2} position={[0, 65.223, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.wdst_low_Material__2_0.geometry} material={materials.Material__2} position={[0, -188.105, 204.147]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[-100.763, 0.206, 19.98]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} position={[0, 0, 0.378]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert4SG} position={[0, 4.14, -4.884]} />
      </group>
      <group position={[-82.846, 20.853, 3.142]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials['Material.002']} position={[9.097, 4.755, 1.902]} rotation={[0.01, 0.084, -0.113]} scale={[2.836, 2.042, 1.361]} />
      </group>
      <group position={[-96.99, 15.429, 9.533]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2002.geometry} material={materials['Material.003']} position={[1.816, 3.805, -7.28]} scale={[1.786, 0.859, 1.7]} />
      </group>
      <group position={[-58.063, 7.489, -11.698]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2003.geometry} material={materials['Material.004']} position={[9.308, -7.765, 1.883]} rotation={[0, 0.088, 0]} scale={[2.416, 1.256, 2.046]} />
      </group>
      <mesh geometry={nodes.Object_2004.geometry} material={materials['lambert3SG.001']} position={[-100.763, 0.206, 19.98]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[-113.533, -12.665, 26.087]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.621, 1, 1.078]}>
        <mesh geometry={nodes.Object_2005.geometry} material={materials['lambert3SG.002']} position={[0, -15.882, 11.091]} scale={[1, 1.092, 1]} />
      </group>
      <group position={[-113.533, -12.665, 26.087]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.621, 1, 1.078]}>
        <mesh geometry={nodes.Object_2006.geometry} material={materials['lambert3SG.003']} position={[0, -15.882, 11.091]} scale={[1, 1.092, 1]} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials['lambert2SG.001']} position={[0, -15.882, 12.538]} scale={[1, 1.092, 1]} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['lambert4SG.001']} position={[0.837, -26.935, 10.814]} />
      </group>
      <group position={[-29.525, -18.446, 18.459]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.503, -1, -1.142]}>
        <mesh geometry={nodes.Object_2007.geometry} material={materials['lambert3SG.004']} position={[17.987, -25.698, 17.071]} scale={[1.551, 1.352, 1]} />
        <mesh geometry={nodes.Object_3002.geometry} material={materials['lambert2SG.002']} position={[17.987, -25.698, 17.071]} scale={[1, 1.352, 1]} />
        <mesh geometry={nodes.Object_4002.geometry} material={materials['lambert4SG.002']} position={[17.987, -25.698, 5.578]} scale={[1, 1.352, 1]} />
      </group>
      <group position={[-29.525, -18.446, 18.459]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.503, -1, -1.142]}>
        <mesh geometry={nodes.Object_2008.geometry} material={materials['lambert3SG.005']} position={[17.987, -25.698, 17.071]} scale={[1, 1.352, 1]} />
      </group>
      <group position={[-39.869, -2.137, 12.352]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.81, -1, -1.059]}>
        <mesh geometry={nodes.Object_2009.geometry} material={materials['lambert3SG.006']} position={[0, 0, 2.756]} />
      </group>
      <group position={[-39.869, -2.137, 12.352]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.81, -1, -1.059]}>
        <mesh geometry={nodes.Object_2010.geometry} material={materials['lambert3SG.007']} position={[0, 0, 2.756]} />
        <mesh geometry={nodes.Object_3003.geometry} material={materials['lambert2SG.003']} position={[0, 0, 2.756]} scale={[0.71, 1, 1]} />
        <mesh geometry={nodes.Object_4003.geometry} material={materials['lambert4SG.003']} position={[0, -7.319, 2.756]} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} position={[-71.219, 1.006, 44.845]} scale={[11.9, 0.679, 11.912]} />
      <mesh geometry={nodes.stage.geometry} material={materials['Material.001']} position={[-71.219, 1.96, 44.845]} scale={[11.53, 0.314, 11.49]} />
    </group>
  )
}

useGLTF.preload('./models/stage/stage3.gltf')
